import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WhatsappChat from "@/components/WhatsappChat";
import ScrollToTop from "@/components/ScrollToTop";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={``}
    >
      <body className="min-h-full flex flex-col">
        {children}
            <ScrollToTop/>
        <WhatsappChat/>
        </body>
    </html>
  );
}
